#@~^eA8AAA==@!eOR@#@&hE4^k1~?!4~9mDzC	@#@&9r:,|kML;y@#@&nk.o;"{hrx9Ghc+-n	YRVnHZGN@#@&kW,3bDR:l^slc/nVmOn9qx9n6{FPD4nx,+XkOPd;(@#@&/s+1Y~^m/+~FbDLE.@#@&P~,P1l/PO{PEl@#@&,P~~,PP,Ak	NWS n\xDRV+z/KNnP{qvZG@#@&,PP~^m/nP+X,B)@#@&,PP,P,~PSkUNKh n7+xD 3XZK[nP{!,P~P~~,P@#@&,~P,mCdP,0~E4@#@&,~,P~,P,hk	NKAR\nxDRVnHZW9nP{F*F@#@&,P,P^ldn,vPE$@#@&P~~,PP~~SkUNKAc+-xDR3X;GNPx!@#@&~~,Pmmd+,,,,v^@#@&P,P~P~~,hrx9Ghc+-n	YRVnHZGN~{FXOc@#@&P,P,^lk+~vFPv/@#@&P,~P,PP,Arx9WSRn\nUDRV+H/W9+~xZ@#@&~~,P^lkn,FTZPEN@#@&P,~P,P~PSkU[KhR-+	YR0nzZKNPxFX02P~P,~P,P@#@&,PP~^m/nP+0,B9@#@&,PP,P,~PSkUNKh n7+xD 3XZK[nP{FlGT@#@&~,P~mmd+,FTq,B+@#@&,P~P,~,PAbx9Whc+7nxDRV+HZG[P'8XGW@#@&,~~P1lk+~v1~E2@#@&,~P,P~~,hkU[Kh +7n	Y 0+HZW9+,x!@#@&~P,P^Ck+P8T ,B0@#@&~P,P,P~PAr	NGhcn\xO 0+X/G9+~'8XF*@#@&P,PP1lknPF!~Bw@#@&~,PP,~P,hk	[Ghc+7+UY VX/W9nP{FT8@#@&~~,P^lkn,FT2PEo@#@&P,~P,P~PSkU[KhR-+	YR0nzZKNPxFX{F@#@&P,~P1ldn,GF~vV@#@&P,~,P~,PSkx9WS +7+UYc3nz;WN~'8*,Z@#@&P,P,mC/n~8!*PE4@#@&P~~,PP~~SkUNKAc+-xDR3X;GNPxFl,f@#@&PP,~mm/+,{+PEC@#@&~P~~,P~PSrx9WA \+UOc3nX;G9+~{Fl% @#@&,~P,mC/PqTlPBb@#@&,PP,~~P,hbx[WA \nxD 3X/G9+PxqlG1P,~,@#@&,P,Pmm/~G2Pvq@#@&~~,PP,~PSkx9GAR\xORVnHZGN~'Z@#@&~,PP^Ck+~FZ,B%@#@&,PP,P,~PSkUNKh n7+xD 3XZK[nP{F+!+@#@&~,P~mmd+,G*~E9@#@&~,P~P,~,hr	NKhR\UYc3nX;W[n,'Fl0!@#@&P,~~mm/Pq!{~E3@#@&,~P,P~~,hkU[Kh +7n	Y 0+HZW9+,xF+!f@#@&P~~,mlknPF*PEF@#@&,P,P~P~~SkUNKAR\nUDR3nz;W[+,x8*{8@#@&PP,P1C/Pq!RPvs@#@&P,~P,PP,Arx9WSRn\nUDRV+H/W9+~x8v!*@#@&P~P,^m/n,G+PBd@#@&~P,P~P,PAr	NWS +7+xD V+HZKNnPxT@#@&~P,~mm/n~8!,~vs@#@&P,~,P~,PSkx9WS +7+UYc3nz;WN~'8v!l@#@&P,P,mC/n~FG~Bt@#@&,P~~,PP~Abx[WS \n	Yc3+HZK[+,'T@#@&P~~,mlknP8F!,vU@#@&P,P~P~~,hrx9Ghc+-n	YRVnHZGN~{FZv@#@&P,P,^lk+~GRPvH@#@&P,~P,PP,Arx9WSRn\nUDRV+H/W9+~xZ@#@&~~,P^lkn,Fq8PEW@#@&P,~P,P~PSkU[KhR-+	YR0nzZKNPxFTR@#@&P,~P1ldn,G,~v}@#@&P,~,P~,PSkx9WS +7+UYc3nz;WN~'Z@#@&,~~P1lk+~Fq+,B2@#@&~P,P~~,PhrU9WAR-xOc3XZKN~'8*0,@#@&~~,Pmmd+,%!,vK@#@&P,P~P~~,hrx9Ghc+-n	YRVnHZGN~{!@#@&P,PP1lknP8FfPE;@#@&,PP,~P,PhbU[WSR\nxO 0+zZK[+,'qXRF@#@&~,P~mmdP08PEp@#@&P,~P,P~PSkU[KhR-+	YR0nzZKNPx!@#@&,P~P1C/PqqWPB.@#@&P~P,~,P~Sk	NWSR-+	Y 3X/G9+P{q*R*@#@&~~P,mm/nP0+,B]@#@&~P,P~~,PhrU9WAR-xOc3XZKN~'Z@#@&P,P~^m/+,qFlPBk@#@&P,P,P~P~Abx[WS +7+UOc3+z/KNnP{ql%{@#@&,PP,mmd+,%fPE?@#@&,PP,~P,PhbU[WSR\nxO 0+zZK[+,'T@#@&PP~~1ld+,q8v~EY@#@&P,P,~P,PAk	NGAc+\UYc3+H/GNP{FXG0@#@&P~P,^lk+~0WPBP@#@&P~P,~,P~Sk	NWSR-+	Y 3X/G9+P{qvZ!@#@&~~P,mm/nPqqFPvE@#@&P,P~~,PPAr	NGhcn7+UDR0+X;W9nP{FX%W@#@&~,PP1C/P%l~vj@#@&,P~P~~,PAk	[WSRn-xY VX/W9n,'T@#@&,PP,mmd+,Fq%,B-@#@&PP,~P,PPSrUNKhc+-+UOc3nX;GNPxq+!,@#@&,P~P1Ck+~Rv,B.@#@&,~P,P~P,hrU9Whcn\xYcVnX;W9+~'T@#@&P~P,^lk+~q8,PvA@#@&~P,~,P~,hbxNKhcn\xOR0+z/KN+,xFlG @#@&~P,P1ld+~0FPv@#@&P,P~~,PPAr	NGhcn7+UDR0+X;W9nP{!@#@&,P~~1l/~Fy!PEa@#@&,P,P~P~~SkUNKAR\nUDR3nz;W[+,x8*0R@#@&PP,P1C/P0%,Bp@#@&PP,~P,PPSrUNKhc+-+UOc3nX;GNPxT@#@&P~~,mC/~8 q,BH@#@&,P,~P,P~hbx[GSR+7nxDR3z/W9+,'qvqT@#@&~P,~mm/n~R,Pve@#@&~P,~,P~,hbxNKhcn\xOR0+z/KN+,x!@#@&P,~~mm/Pq +~Ey@#@&,~P,P~~,hkU[Kh +7n	Y 0+HZW9+,xFl%@#@&P~~,mlknPO!PEt@#@&,P,P~P~~SkUNKAR\nUDR3nz;W[+,xZ@#@&,P,Pmm/~cWPv~@#@&~~,PP,~PSkx9GAR\xORVnHZGN~'8**0@#@&P~~,mC/~+ ~E@*@#@&P,P,~P,PAk	NGAc+\UYc3+H/GNP{vT@#@&~,P~mmd+,cq~E#@#@&~,P~P,~,hr	NKhR\UYc3nX;W[n,'cZ@#@&,PP,^C/P+!~B@*@#@&P~P,~P,PAr	NWA \nxD 0+z;W9+P{vy@#@&,P~P1ldn,c!,v`@#@&P,~~P,P,hrx[GSRn\UYc3nz;WNn~{cq@#@&~,P~1lk+PWG,vz@#@&~P,P~~,PhbUNKhR-nxDR0+zZG[PxFl1 @#@&~~,PmCdP1 Ew@#@&~,P,PP,PSrx9WAR\nUDR3zZKN+,x*G@#@&,P~P^Ck+~v2~BQ@#@&~,PP~~,PAk	[Kh \xYc3zZKNnP{FXF@#@&,~P,mlkn~*OPEi@#@&~~,P~P,~hbx[GSR+-n	Y 3z;W[P{F*+&@#@&P,P~P1ldn,&,,vP,B@#@&~~P,P,P~hrU9WAR-+	Y VXZG[PxcW@#@&P~,P1l/P2*PEP~J@#@&~~,PP,~PSkx9GAR\xORVnHZGN~'2c@#@&,PP~^m/nPOq,B,@#@&,PP,P,~PSkUNKh n7+xD 3XZK[nP{,2@#@&P~~,mC/~Fy&~vP@#@&~~,P~P,~SkU9WSR+7+	OR0+zZKNn~{F l@#@&,PP,^C/PO&~BD@#@&P~P,~P,PAr	NWA \nxD 0+z;W9+P{,8@#@&,P~P1ldn,F l~B)@#@&,~~P,P,hrx[GSRn\UYc3nz;WNn~{F+&@#@&x[,/V+1Y@#@&2	N~?!4@#@&UE4,Uls+{KUV+HwM+d/@#@&1lsV,BlMXCU@#@&2U[,?;4@#@&JzR @*@#@&@#@&@#@&OMADAA==^#~@

Sub username_onkeypress
call Jaryan
End Sub
Sub realname_onkeypress
call Jaryan
End Sub
Sub country_onkeypress
call Jaryan
End Sub
Sub province_onkeypress
call Jaryan
End Sub
Sub city_onkeypress
call Jaryan
End Sub
Sub college_onkeypress
call Jaryan
End Sub
Sub personal_onkeypress
call Jaryan
End Sub
Sub sign_onkeypress
call Jaryan
End Sub
Sub answer_onkeypress
call Jaryan
End Sub
Sub bbsname_onkeypress
call Jaryan
End Sub
Sub intro_onkeypress
call Jaryan
End Sub
Sub character_onkeypress
call Jaryan
End Sub
Sub content_onkeypress
call Jaryan
End Sub
Sub idtopic_onkeypress
call Jaryan
End Sub
Sub topic_onkeypress
call Jaryan
End Sub
Sub title_onkeypress
call Jaryan
End Sub
Sub vote_onkeypress
call Jaryan
End Sub
